#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./parabolic/Allclean
./tracer/Allclean
./coupling/Allclean
./transfers/Allclean
./injections/Allclean
./bubbles/Allclean
./boundaries/Allclean
./VoF/Allclean

