#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./parabolic/Allrun
./tracer/Allrun
./coupling/Allrun
./transfers/Allrun
./injections/Allrun
./bubbles/Allrun
./boundaries/Allrun
./VoF/Allrun

