#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication blockMesh
export ENV_EOS=PengRobinson
runApplication -s $ENV_EOS Test-cubicEOS -eos $ENV_EOS -mixture
export ENV_EOS=RedlichKwong
runApplication -s $ENV_EOS Test-cubicEOS -eos $ENV_EOS -mixture