/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Copyright (C) 2026 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::printDictionary

Description
    Enables the printing of a dictionary
    and subsequently looked-up defaulted entries

SourceFiles
    printDictionary.C

\*---------------------------------------------------------------------------*/

#ifndef printDictionary_H
#define printDictionary_H

#include "HashPtrTable.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

class dictionary;

/*---------------------------------------------------------------------------*\
                          Class printDictionary Declaration
\*---------------------------------------------------------------------------*/

class printDictionary
{
private:

    // Private Static Data

        //- Table from the names of dictionaries to be printed to pointers
        //  to those dictionaries
        static HashTable<const dictionary*, fileName, Hash<fileName>>
            dictNameToDictPtrs_;

        //- Table from pointers to the dictionaries to be printed to
        //  dictionaries containing all entries including defaults
        static HashPtrTable<dictionary, const dictionary*, Hash<void*>>
            dictPtrToDefaults_;

        //- Pointer to the dictionary to be printed
        const dictionary* dictPtr_;

        //- Name of the dictionary to be printed
        const fileName dictName_;


public:

    // Constructors

        //- Construct for model sub-dictionary. Use this for things like
        //  fvModels which read a sub-dictionary, and do not own or construct
        //  their own IOdictionary.
        printDictionary(const dictionary& dict);

        //- Construct for a dictionary name. Use this for classes like
        //  momentumTransportModels which do own and construct their
        //  IOdictionary as part of their construction.
        printDictionary(const fileName& dictName);


    //- Destructor
    ~printDictionary();


    // Member Functions

        //- Set the dictionary to be printed
        static void set(const dictionary& dict);

        //- Un-set the dictionary to be printed
        static void unset(const dictionary& dict);

        //- Return if a dictionary is marked to be printed
        static bool prints(const dictionary& dict)
        {
            return dictNameToDictPtrs_.found(dict.name());
        }

        //- Return if a dictionary is marked to be printed
        static bool prints(const word& dictName)
        {
            return dictNameToDictPtrs_.found(dictName);
        }

        //- Return if a dictionary exists to add defaults to for a given
        //  dictionary
        static bool haveDefaults(const dictionary& dict)
        {
            return dictPtrToDefaults_.found(&dict);
        }

        //- Return the dictionary to add defaults to for a given dictionary
        static dictionary& defaults(const dictionary& dict)
        {
            return dictPtrToDefaults_[&dict];
        }
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
